# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7
  
stages: test

jobs:
   postman_tests:
       stage: test
       image: 
           name: postman/newman_alpine33
           entrypoint: [""]
      script:
           - newman --version

workflows:
  sample:
    jobs:
      - postman_tests
       
